name: Benchmark PR

on: pull_request

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      PR_TIME: ""
      BASE_TIME: ""
      PERCENT_CHANGE: ""

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run benchmark on PR branch
        id: pr_benchmark
        run: |
          PR_TIME=$(time node ./benchmarks/run.js |& grep real | awk '{print $2}')
          echo "PR_TIME=${PR_TIME}" >> $GITHUB_ENV

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Checkout head benchmarks
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.base.ref }} -- benchmarks

      - name: Run benchmark on base branch
        id: base_benchmark
        run: |
          cd benchmarks
          BASE_TIME=$(time node ../benchmarks/run.js |& grep real | awk '{print $2}')
          echo "BASE_TIME=${BASE_TIME}" >> $GITHUB_ENV

      - name: Calculate percent change
        id: percent_change
        run: |
          percent_change=$(echo "scale=2; ((${PR_TIME}s - ${BASE_TIME}s) / ${BASE_TIME}s) * 100" | bc)
          echo "PERCENT_CHANGE=${percent_change}" >> $GITHUB_ENV

      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Benchmark Results"

      - name: Comment on PR with benchmark results
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Benchmark Results

            | Benchmark     | PR Branch Time | Base Branch Time | Percent Change |
            |---------------|-----------------|------------------|----------------|
            | Total Time    | ${PR_TIME}s | ${BASE_TIME}s | ${PERCENT_CHANGE}% |            edit-mode: replace
          edit-mode: replace
